#!/usr/bin/env bash

set -e

SCRIPTDIR="$(cd "${pwd}")"
ROOTDIR="$(cd "${SCRIPTDIR}" && pwd)"

set -x

cat > "${ROOTDIR}/AUTHORS" <<- EOF
	# File are generated by test/aut/gen-authors.sh.
	# This file lists all contributors to the repository.
	# See test/aut/gen-authors.sh to make modifications.

	$(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF